export const SET_CURRENCY = 'SET_CURRENCY';
export const CHANGE_CURRENCY = 'CHANGE_CURRENCY';

export const FETCH_EXCHANGE_RATE_START = 'FETCH_EXCHANGE_RATE_START';
export const FETCH_EXCHANGE_RATE_SUCCESS = 'FETCH_EXCHANGE_RATE_SUCCESS';
export const FETCH_EXCHANGE_RATE_FAILED = 'FETCH_EXCHANGE_RATE_FAILED';